name: Build

on:
    pull_request:
        branches: ["dev"]

env:
    BUILD_TYPE: Release

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup emsdk
              uses: mymindstorm/setup-emsdk@v11
              with:
                  version: 3.1.37
                  actions-cache-folder: "emsdk-cache"
            - name: CD to workspace
              run: cd ${{github.workspace}}
            - name: Configure
              run: emcmake cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
            - name: Build
              run: emmake cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
